modLoader="javafml"
loaderVersion="[36,)"

license="MIT"
issueTrackerURL="https://github.com/yermolim/keep-the-rain/issues"

[[mods]]
    modId="keeptherain"
    version="${file.jarVersion}"
    displayName="Keep The Rain"
    updateJSONURL="https://github.com/yermolim/keep-the-rain/blob/master/update.json"
    displayURL="https://github.com/yermolim/keep-the-rain/releases"
    logoFile="logo.png"
    credits="made by yermolim"
    authors="yermolim"
    description='''
    Keep the rain!
    A simple server side mod that prevents rain timer from resetting after sleep and gives a chance for rain to continue after players woke up.
    '''
[[dependencies.keeptherain]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.keeptherain]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
